### ISSUE TITLE
How to use `fontWeight: 'bold'`

### ISSUE THREAD

**Issue by GeMiNiOranGe** [charmy/react-native-stroke-text#26]
I don't know how to use `fontWeight: 'bold'`, i can't find any prop that allows passing `bold` value

**Comment by ozgursoy** [comment]
http://www.catb.org/esr/faqs/smart-questions.html

**Comment by GeMiNiOranGe** [comment]
> http://www.catb.org/esr/faqs/smart-questions.html

I'm sorry, I just updated my issue.

**Comment by ozgursoy** [comment]
You should check closed issues before openning new one. It's an open source project not an help center. 

`fontWeight` prop removed due to inconsistency between platforms but you can use all font weights with custom font implementation. All you need to do download the font you want to use.
https://github.com/charmy/react-native-stroke-text?tab=readme-ov-file#custom-font

**Bold**
```tsx
<StrokeText fontFamily="Nunito-Bold"/>
```

Regular
```tsx
<StrokeText fontFamily="Nunito-Regular"/>
```
